export const emberekLISTA =[
    {nev: "Éva",
    kor:12,
    nem:true},
    {nev: "Ádám",
    kor:22,
    nem:false},
    {nev: "Jenő",
    kor:32,
    nem:false},
    {nev: "béla",
    kor:13,
    nem:false},
    {nev: "Anna",
    kor:42,
    nem:true},
]